<?php
/**
 * Edit Affiliate template
 */
?>
<?php
$store_id = Mage::app()->getStore()->getStoreId();
$check_responsvie = Mage::getStoreConfig('affiliateplus/style_config/responsive_enable', $store_id);
$account = $this->getAccount();
// var_dump($account->getData());die();
$content = '<table style="margin: auto;" border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td>
<table style="height: 173px; width: auto;">
<tbody>
<tr>
<td style="width: 65%;">
<h1><span>YOUR TITLE HERE</span></h1>
</td>
<td style="width: 35%;"><img src="http://placehold.it/600x200" border="0" width="151" height="150" /></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>';
if($check_responsvie){
    $class_name = 'col-lg-9 col-md-9 col-sm-12 col-xs-12';
    $class_name_col = 'col-lg-6 col-md-6 col-sm-12 col-xs-12';
}
else{
    $class_name = 'col-lg-9 col-md-9 col-sm-9 col-xs-9';
    $class_name_col = 'col-lg-6 col-md-6 col-sm-6 col-xs-6';
}
?>

<div class="aff-main-content  <?php echo $class_name; ?>">
    <div class="aff-title">
        <h1><?php echo $this->__('Sub store link') ?></h1>
    </div>
    <?php if($account->getKeyShop()):?>
        <div class="affiliate-get-link fieldset">
            <ul class="form-list">
                <li class="wide">
                    <p><?php echo $this->__('Sub store link') ?>:</p>
                    <a id="affiliate-link" href="<?php echo $this->getAffiliateUrl() ?>" rel="nofollow" title="<?php echo $this->__('Sub store link') ?>"><?php echo $this->getAffiliateUrl() ?></a>
                </li>
                <li>
                    <p><?php echo $this->__('Sub store banner:') ?></p>
                    <form id="substore_affiliate_banner_form" method="post" action="<?php echo $this->getUrl('affiliateplus/account/editPageBanner') ?>">
                        <div class="" style="margin-top:-50px;">
                            <ul class="form-list">
                                <li class="fields">
                                    <div class="field">
                                        <label><?php echo $this->__('Description') ?></label>
                                        <div class="input-box">
                                            <textarea cols="15" rows="2" name="substore_description" id="substore_description">
                                            <?php 
                                                if(is_null($account->getDescription())){
                                                   echo  $content;
                                                }else{
                                                    echo $account->getDescription();
                                                }
                                            ?>
                                            </textarea>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="buttons-set">
                            <p class="required">* <?php echo $this->__('Required Fields'); ?></p>
                            <button class="button button-config" type="submit" title="Save">
                                <span><span ><?php echo $this->__('Save') ?></span></span>
                            </button>
                        </div>
                    </form>
                </li>
            </ul>
        </div>
        <br />
    <?php else: ?>
        <div>
            <p class="note-msg">
                <?php echo $this->__('There are no substore available.') ?>
            </p>
        </div>
    <?php endif;?>
</div>
<script type="text/javascript" src="<?php echo $this->getBaseUrl().'js/tiny_mce/tinymce.min.js';?>"></script>
<script type="text/javascript">
    
// window.onload=function()
// {
    tinymce.init({ 
        selector:'#substore_description',
        theme: 'modern',
        relative_urls: false,
        remove_script_host: false,
        plugins: [
        'advlist autolink lists link image charmap print preview hr anchor pagebreak',
        'searchreplace wordcount visualblocks visualchars code fullscreen',
        'insertdatetime media nonbreaking save table contextmenu directionality',
        'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc responsivefilemanager'
        ],
        toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        toolbar2: 'responsivefilemanager | print preview media | forecolor backcolor emoticons | codesample',
        image_advtab: true,
        templates: [
        { title: 'Test template 1', content: 'Test 1' },
        { title: 'Test template 2', content: 'Test 2' }
        ],
        external_filemanager_path:"<?php echo $this->getBaseUrl().'filemanager/';?>",
        filemanager_title:"Responsive Filemanager" ,
        external_plugins: { "filemanager" : "<?php echo $this->getBaseUrl().'filemanager/plugin.min.js';?>"}
    });
  //  tinyMCE.init({
  //   mode : "exact",
  //   elements: "substore_description",
  //   theme : "advanced",
  //   plugins : "inlinepopups,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
  //   theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
  //   theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
  //   theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
  //   theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
  //   theme_advanced_toolbar_location : "top",
  //   theme_advanced_toolbar_align : "left",
  //   theme_advanced_path_location : "bottom",
  //   extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
  //   theme_advanced_resize_horizontal : 'true',
  //   theme_advanced_resizing : 'true',
  //   apply_source_formatting : 'true',
  //   convert_urls : 'false',
  //   force_br_newlines : 'true',
  //   doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'

  // });

// };
</script>
